# Generated by Django 3.2.6 on 2022-01-29 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMarca', models.CharField(max_length=255)),
                ('logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TiposCarros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MecanicosRevisores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Carros', to='carros.marcas')),
                ('especialidadeTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Carros', to='carros.tiposcarros')),
            ],
            options={
                'verbose_name_plural': 'Mecanicos',
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeCarro', models.CharField(max_length=255)),
                ('cilindradas', models.FloatField()),
                ('preco', models.FloatField()),
                ('quantidadeDonos', models.IntegerField()),
                ('kilometragem', models.FloatField()),
                ('dataPublicacao', models.DateField()),
                ('ano', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='carros.anos')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NaN', to='carros.marcas')),
                ('revisor', models.ManyToManyField(related_name='Mecanico', to='carros.MecanicosRevisores')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NaN', to='carros.tiposcarros')),
            ],
        ),
    ]
