# Generated by Django 3.2.6 on 2022-01-29 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processos', models.IntegerField(choices=[(1, 'Documentos Cliente'), (2, 'Pagamento'), (3, 'Veiculo Liberado'), (4, 'Finalizado, Entregue')], default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aluga', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processos', models.IntegerField(choices=[(0, 'Comprador Demonstrou Interesse'), (1, 'Documentos Comprador'), (2, 'Pagamento Comprador'), (3, 'Tranferencia Documental Veiculo'), (4, 'Processo Finalizado')], default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendendoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aluga', to='carros.compra')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carro', to='carros.carro')),
            ],
        ),
        migrations.CreateModel(
            name='AlugandoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugango_carro', to='carros.aluga')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculo', to='carros.carro')),
            ],
        ),
    ]
