# Generated by Django 3.2.6 on 2022-02-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_aluga_alugandouser_compra_vendendouser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendendouser',
            old_name='aluga',
            new_name='compra',
        ),
    ]
